In [35]:
import numpy as np
from arktypes import joint_group_command_t, task_space_command_t, joint_state_t
from arktypes.utils import unpack, pack
from ark.client.comm_infrastructure.instance_node import InstanceNode

SIM = True

class KukaControllerNode(InstanceNode):

    def __init__(self):
        '''
        Initialize the KukaJointController.
        This class is responsible for controlling the Kuka robot's joints.
        '''
        super().__init__("KukaJointController")

        if SIM == True:
            self.joint_group_command = self.create_publisher("Kuka/joint_group_command/sim", joint_group_command_t)
            self.task_space_command = self.create_publisher("Kuka/cartesian_command/sim", task_space_command_t)

            self.state = self.create_listener("Kuka/joint_states/sim", joint_state_t)

controller = KukaControllerNode()

[WARNING] [13:48:38.378525] - No global configuration provided. Using default system configuration.
[INFO] [13:48:38.394367] - Service: Successfully registered '__DEFAULT_SERVICE/GetInfo/KukaJointController_c8103d52-ab48-436f-83b3-1c4d06a0c427' with registry.
[INFO] [13:48:38.503294] - Service: Successfully registered '__DEFAULT_SERVICE/SuspendNode/KukaJointController_c8103d52-ab48-436f-83b3-1c4d06a0c427' with registry.
[INFO] [13:48:38.520065] - Service: Successfully registered '__DEFAULT_SERVICE/RestartNode/KukaJointController_c8103d52-ab48-436f-83b3-1c4d06a0c427' with registry.
[ERROR] [13:48:38.522830] - Couldn't load config for other 'KukaJointController'
[OK] [13:48:38.532545] - setup publisher Kuka/joint_group_command/sim[joint_group_command_t]
[OK] [13:48:38.533822] - setup publisher Kuka/cartesian_command/sim[task_space_command_t]
[OK] [13:48:38.535779] - subscribed to Kuka/joint_states/sim[joint_state_t]


None


---

# Joint Group Control

In [40]:
joint_command = [-0.3, 0.1, 0.3, -1.4, 0.1, 1.8 ,2]
# Position Control
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "all"))

In [41]:
arm_command = [-0.1, -0.5, -0.3, 1.0, -0.1, -1.8, 1]
# Position Control 
controller.joint_group_command.publish(pack.joint_group_command(arm_command, "arm"))

---

# Task Space Control

In [42]:
xyz_command = np.array([0.3, 0.4, 0.8])
quaternion_command = np.array([1, 0.0, 0.0, 0.0]) # xyz-w

controller.task_space_command.publish(
    pack.task_space_command("all", xyz_command, quaternion_command)
)

---

# Joint States

In [44]:
unpack.joint_state(controller.state.get())

({'seq': 0, 'stamp': {'sec': 0, 'nsec': 0}, 'frame_id': ''},
 ['kuka_arm_0_joint',
  'kuka_arm_1_joint',
  'kuka_arm_2_joint',
  'kuka_arm_3_joint',
  'kuka_arm_4_joint',
  'kuka_arm_5_joint',
  'kuka_arm_6_joint'],
 array([ 0.94613295, -0.31543036, -0.08368051,  1.25144731,  0.02817042,
        -1.57956562,  2.96705973]),
 array([0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0.]))