In [1]:
import numpy as np
from arktypes import joint_group_command_t, task_space_command_t, joint_state_t
from arktypes.utils import unpack, pack
from ark.client.comm_infrastructure.instance_node import InstanceNode

SIM = True

class XarmControllerNode(InstanceNode):

    def __init__(self):
        '''
        Initialize the XarmJointController.
        This class is responsible for controlling the Xarm robot's joints.
        '''
        super().__init__("XarmJointController")

        if SIM == True:
            self.joint_group_command = self.create_publisher("Xarm/joint_group_command/sim", joint_group_command_t)
            self.task_space_command = self.create_publisher("Xarm/cartesian_command/sim", task_space_command_t)

            self.state = self.create_listener("Xarm/joint_states/sim", joint_state_t)

controller = XarmControllerNode()

[WARNING] [14:49:47.016520] - No global configuration provided. Using default system configuration.
[INFO] [14:49:47.020202] - Service: Successfully registered '__DEFAULT_SERVICE/GetInfo/XarmJointController_f1360507-ae87-4169-867a-fb65344d1860' with registry.
[INFO] [14:49:47.022390] - Service: Successfully registered '__DEFAULT_SERVICE/SuspendNode/XarmJointController_f1360507-ae87-4169-867a-fb65344d1860' with registry.
[INFO] [14:49:47.024116] - Service: Successfully registered '__DEFAULT_SERVICE/RestartNode/XarmJointController_f1360507-ae87-4169-867a-fb65344d1860' with registry.
[ERROR] [14:49:47.024752] - Couldn't load config for other 'XarmJointController'
[OK] [14:49:47.025866] - setup publisher Xarm/joint_group_command/sim[joint_group_command_t]
[OK] [14:49:47.027392] - setup publisher Xarm/cartesian_command/sim[task_space_command_t]
[OK] [14:49:47.028736] - subscribed to Xarm/joint_states/sim[joint_state_t]


None


---

# Joint Group Control

In [93]:
joint_command = [-1, 0.1, 0.3, -1.4, 1]
# Position Control
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "all"))

In [94]:
arm_command = [-2, -1, 1.1, -0.6, 0.2]
# Position Control 
controller.joint_group_command.publish(pack.joint_group_command(arm_command, "arm"))

---

# Task Space Control

In [103]:
xyz_command = np.array([0.3, 0.4, 0.8])
quaternion_command = np.array([1, 0.0, 0.0, 0.0]) # xyz-w

controller.task_space_command.publish(
    pack.task_space_command("all", xyz_command, quaternion_command)
)

---

# Joint States

In [44]:
unpack.joint_state(controller.state.get())

({'seq': 0, 'stamp': {'sec': 0, 'nsec': 0}, 'frame_id': ''},
 ['xarm_arm_0_joint',
  'xarm_arm_1_joint',
  'xarm_arm_2_joint',
  'xarm_arm_3_joint',
  'xarm_arm_4_joint',
  'xarm_arm_5_joint',
  'xarm_arm_6_joint'],
 array([ 0.94613295, -0.31543036, -0.08368051,  1.25144731,  0.02817042,
        -1.57956562,  2.96705973]),
 array([0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0.]))